# Generated by Django 3.2.6 on 2021-08-04 06:19

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Account', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='extendeduser',
            name='birthdate',
            field=models.DateField(null=True),
        ),
    ]
