# Generated by Django 3.2.6 on 2021-08-04 18:32

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Account', '0002_alter_extendeduser_birthdate'),
    ]

    operations = [
        migrations.AddField(
            model_name='extendeduser',
            name='joined_date',
            field=models.DateTimeField(null=True),
        ),
    ]
